apiVersion: v2
name: eir
version: 1.0.1
type: application
description: A Helm chart for deploying the Eir metrics collector
appVersion: "1.0.1"


apiVersion: v2
appVersion: "1.0.1"
description: A Helm chart for deploying the Eir metrics collector
name: eir
keywords:
  - monitoring
  - metrics
  - collector
sources:
  - https://github.com/Margays/eir
maintainers:
  - name: lwencel-priv
    email: lwencel@margays.dev
    url: https://github.com/lwencel-priv
version: 1.0.1
